<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>source-to-markdown</AssemblyName>
		<RootNamespace>SourceToMarkdown</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Tests/**/*.cs" />
		<EmbeddedResource Remove="Tests/**" />
		<None Remove="Tests/**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="GitignoreParserNet" Version="0.2.0.15" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.0" />
	</ItemGroup>
	<ItemGroup>
		<None Include="appsettings.language-map.json" CopyToOutputDirectory="PreserveNewest" />
		<None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
